import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Tabs, Tab, Box } from "@mui/material";
import { TabPanel } from "../components/TabPanel";
import FEBETab from "../components/FEBETab";
import APITab from "../components/APITab";
import PackagesTab from "../components/PackagesTab";
import * as React from "react";

export default function Home() {
  const [value, setValue] = React.useState(0);

  const handleChange = (event, newValue) => {
    setValue(newValue);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Mannheimer swartling demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Mannheimer Swartling Demo</h1>

        <Box
          sx={{
            borderBottom: 1,
            borderColor: "divider",
            width: "50%"
          }}
        >
          <Tabs
            centered
            value={value}
            onChange={handleChange}
            aria-label="basic tabs example"
            className={styles.tabsContainer}
          >
            <Tab label="Frontend vs Backend" id="1" />
            <Tab label="API" id="2" />
            <Tab label="Packages" id="3" />
          </Tabs>
          <TabPanel value={value} index={0}>
            <FEBETab />
          </TabPanel>
          <TabPanel value={value} index={1}>
            <APITab />
          </TabPanel>
          <TabPanel value={value} index={2}>
            <PackagesTab />
          </TabPanel>
        </Box>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://biancajemsten.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Coded by{" "}
          <span className={styles.logo}>
            <Image src="/b-logo.png" alt="B Logo" width={16} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
